---
title: "Tugas Praktikum MPDW 1"
author: "Fedora"
date: "2023-08-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Library yang digunakan
```{r}
library("forecast")
library("graphics")
library("TTR")
library("TSA")
library("rio")
```

#Impor Data
```{r}
data.turis <- import("Data Pendatang Mancanegara di Bali - Sheet1.csv")
data.turis
```

#Eksplorasi Data
```{r}
View(data.turis)
str(data.turis)
dim(data.turis)
```

Mengubah data agar terbaca sebagai data deret waktu dengan fungsi `ts()` .
```{r}
dataturis.ts <- ts(data.turis$Jumlah)
dataturis.ts
```

Menampilkan ringkasan data
```{r}
summary(dataturis.ts)
```

Membuat plot data deret waktu
```{r}
ts.plot(dataturis.ts, xlab="Time Period", ylab="Pendatang Mancanegara", 
        main = "Time Series Plot")
points(dataturis.ts)
```

#Single Moving Average & Double Moving Average
## Pembagian Data

Pembagian data latih dan data uji dilakukan dengan perbandingan 80% data latih dan 20% data uji.
```{r}
#membagi data latih dan data uji
training_ma <- data2[1:96,]
testing_ma <- data2[97:120,]
train_ma.ts <- ts(training_ma$Sales)
test_ma.ts <- ts(testing_ma$Sales)
```